### ISSUE TITLE
 partresize: Ubuntu support

### ISSUE THREAD

**Issue by syphernl** [alpacacode/Homebrewn-Scripts#1]
For Ubuntu the `/etc/rc.d/rc.local` needs to become `/etc/rc.local`. 

After this adaption the script (prior to the reboot) seems to work fineish:

```
root@testvm:~# ./fixme.sh -p /dev/sda5 -l /dev/ubuntu-vg/root -f

This will now extend partition number 5 on disk /dev/sda using start sector 501760.

Model: VMware Virtual disk (scsi)
Disk /dev/sda: 41943040s
Sector size (logical/physical): 512B/512B
Partition Table: msdos

Number  Start    End        Size       Type      File system  Flags
 1      2048s    499711s    497664s    primary   ext2         boot
 2      501758s  33552383s  33050626s  extended
 5      501760s  33552383s  33050624s  logical                lvm

Error: Partition(s) 5 on /dev/sda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
Error: You requested a partition from 257MB to 21,5GB.
The closest location we can manage is 17,2GB to 21,5GB.
Error: Partition doesn't exist.
Model: VMware Virtual disk (scsi)
Disk /dev/sda: 41943040s
Sector size (logical/physical): 512B/512B
Partition Table: msdos

Number  Start    End        Size       Type      File system  Flags
 1      2048s    499711s    497664s    primary   ext2         boot
 2      501758s  33552383s  33050626s  extended

Done. The system will reboot automatically in 15 seconds and resize the filesystem during reboot.

```

Something has failed, but the script proceeds and still issues a reboot which results in it dropping to a busybox shell as it cannot find the volumegroup.

**Comment by syphernl** [comment]
Debug output of the failing part:

```
+ parted /dev/sda --script rm 5
Error: Partition(s) 5 on /dev/sda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
+ parted /dev/sda --script 'mkpart primary ext2 501760s -1s'
Error: You requested a partition from 257MB to 18,3GB.
The closest location we can manage is 17,2GB to 18,3GB.
+ parted /dev/sda --script set 5 lvm on
Error: Partition doesn't exist.
```

**Comment by alpacacode** [comment]
Thanks for the report, I can reproduce it on Ubuntu 14.04.2 LTS.

The issue is that RHEL/CentOS, for which I wrote and tested this script, by default use a primary partition for the LVM like this:

> **Number  Start     End        Size       Type     File system  Flags
> 1      2048s     1026047s   1024000s   primary  ext4         boot
> 2      1026048s  31457279s  30431232s  primary               lvm**

Ubuntu however uses a logical partition layout like this:

> **Number  Start    End        Size       Type      File system  Flags
> 1      2048s    499711s    497664s    primary   ext2         boot
> 2      501758s  41940991s  41439234s  extended
> 5      501760s  41940991s  41439232s  logical                lvm**

I will add some additional checks and logic to cope with logical partitions and make the script more agnostic.

**Comment by alpacacode** [comment]
I've added handling for logical partitions and successfully tested it with Ubuntu 14.04 LTS, try the new version:
https://github.com/alpacacode/Homebrewn-Scripts/commit/79888c0d49496a3e6e62aa6613b6f503cdd54ef8

**Comment by syphernl** [comment]
Awesome, this works like a charm!
