### ISSUE TITLE
partresize.sh is not compatible with Bash 3

### ISSUE THREAD

**Issue by at-boy** [alpacacode/Homebrewn-Scripts#2]
Trying to run partresize.sh under Bash 3 will give

./partresize.sh: line 40: ${response,,}: bad substitution

${response,,} is not compatible with Bash 3

**Comment by alpacacode** [comment]
Should work now with bash>3.2 as well, try the latest commit: https://github.com/alpacacode/Homebrewn-Scripts/commit/a2851e34fa679f409a4a30bb686fb2fcc68750cd

**Comment by alpacacode** [comment]
Fixed in https://github.com/alpacacode/Homebrewn-Scripts/commit/a2851e34fa679f409a4a30bb686fb2fcc68750cd
